language: python

python:
    - "2.7"
    - "3.4"

env:
    - DJANGO_VERSION=1.6.7 TESTPROJECT=testproject
    - DJANGO_VERSION=1.7.7 TESTPROJECT=testproject
    - DJANGO_VERSION=1.8.4 TESTPROJECT=testproject
    - DJANGO_VERSION=1.9 TESTPROJECT=testproject

branches:
    only:
        - develop

matrix:
    exclude:

        -
            python: "3.4"
            env: DJANGO_VERSION=1.6.7 TESTPROJECT=testproject

install:
    - pip install django==$DJANGO_VERSION

script:
    - cd $TESTPROJECT
    - python manage.py test
